// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLUd5OfeMA6oPe0L9GYi8zwkb4EZ7v9yM',
    appId: '1:763797954596:android:e44e850dd05bea05bf78b1',
    messagingSenderId: '763797954596',
    projectId: 'zoomclone-61dc8',
    storageBucket: 'zoomclone-61dc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDOrR4UCJzL_XPn3g5R-Mb6gRWzR4G8AI',
    appId: '1:763797954596:ios:1e6bf7fca7caae5dbf78b1',
    messagingSenderId: '763797954596',
    projectId: 'zoomclone-61dc8',
    storageBucket: 'zoomclone-61dc8.appspot.com',
    androidClientId: '763797954596-1557sdufj1hpl41unf629q4qsciuar24.apps.googleusercontent.com',
    iosClientId: '763797954596-8k167a9pcu3m14iu0rcgqe58uivdegic.apps.googleusercontent.com',
    iosBundleId: 'com.example.books',
  );
}
